export const POST_FORM_TOGGLE = 'POST_FORM_TOGGLE';
// remove the next 3 unnecessary lines
export const POST_FORM_DESCRIPTION = 'POST_FORM_DESCRIPTION';
export const POST_FORM_IMAGE_INDEX = 'POST_FORM_IMAGE_INDEX';
export const POST_FORM_LIKES = 'POST_FORM_LIKES';
export const ADD_POST = 'ADD_POST';
export const RESET_POST_FORM = 'RESET_POST_FORM';
export const OPEN_RESET_POST_FORM_SNACKBAR = 'OPEN_RESET_POST_FORM_SNACKBAR';
export const CLOSE_RESET_POST_FORM_SNACKBAR = 'CLOSE_RESET_POST_FORM_SNACKBAR';
