export const POST_FORM_TOGGLE = 'POST_FORM_TOGGLE';
export const POST_FORM_TITLE = 'POST_FORM_TITLE';
export const POST_FORM_DESCRIPTION = 'POST_FORM_DESCRIPTION';
export const POST_FORM_IMAGE_INDEX = 'POST_FORM_IMAGE_INDEX';
export const POST_FORM_LIKES = 'POST_FORM_LIKES';