export const POST_FORM_TOGGLE = 'POST_FORM_TOGGLE';
export const ADD_POST = 'ADD_POST';
export const OPEN_RESET_POST_FORM_SNACKBAR = 'OPEN_RESET_POST_FORM_SNACKBAR';
export const CLOSE_RESET_POST_FORM_SNACKBAR = 'CLOSE_RESET_POST_FORM_SNACKBAR';
